default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight and submit for external review"
  lane :beta do |options|
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY"],
      is_key_content_base64: false
    )

    gym(
      scheme: "NetNewsWire-iOS",
      project: "NetNewsWire.xcodeproj",
      export_method: "app-store",
      export_options: {
        method: "app-store",
        teamID: "ZVWN4UJS9M",
        manageAppVersionAndBuildNumber: true
      },
      xcargs: "DEVELOPMENT_TEAM=ZVWN4UJS9M ORGANIZATION_IDENTIFIER=io.github.mshibanami CURRENT_PROJECT_VERSION=#{options[:build_number]}"
    )

    pilot(
      api_key: api_key,
      distribute_external: true,
      skip_waiting_for_build_processing: false,
      changelog: "Automated build from GitHub Actions"
    )
  end
end

platform :mac do
  desc "Push a new build to App Store Connect for Mac"
  lane :release do |options|
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY"],
      is_key_content_base64: false
    )

    gym(
      scheme: "NetNewsWire",
      project: "NetNewsWire.xcodeproj",
      export_method: "app-store",
      export_options: {
        method: "app-store",
        teamID: "ZVWN4UJS9M"
      },
      xcargs: "DEVELOPMENT_TEAM=ZVWN4UJS9M ORGANIZATION_IDENTIFIER=io.github.mshibanami CURRENT_PROJECT_VERSION=#{options[:build_number]}"
    )

    pilot(
      api_key: api_key,
      distribute_external: true,
      skip_waiting_for_build_processing: false,
      changelog: "Automated build from GitHub Actions"
    )
  end
end
